# Generated by Django 2.1.3 on 2018-11-01 16:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic=False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bucket_lists_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BucketListModel',
            new_name='BucketListsModel',
        ),
    ]
